### ISSUE TITLE
Is there a way to take screenshot of a selector?

### ISSUE THREAD

**Issue by quanghoc** [schnerd/chrome-headless-screenshots#11]
Let say if I am only interested in one DOM node and want a screenshot of just that. How to do it? Beside finding the DOM coordinates and cut it manually or via other modules.

**Comment by elisherer** [comment]
You can check the code of [Navalia](https://github.com/joelgriffith/navalia)

**Comment by schnerd** [comment]
> Beside finding the DOM coordinates and cut it manually or via other modules.

That seems like the best option as of right now.

There are currently no plans to support that functionality in this repo. Check out [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer), you could use page.evaulate to get the dom coordinates and then page.screenshot with the clip option to screenshot just those coordinates.
