### ISSUE TITLE
fullPage option does not work

### ISSUE THREAD

**Issue by CaledoniaProject** [schnerd/chrome-headless-screenshots#14]
I'm using the following method to take screenshot of a scrollable page

> node index.js --url="https://jonathanmh.com/taking-full-page-screenshots-headless-chrome/" --fullPage

But the output it like this, 

![output](https://user-images.githubusercontent.com/1357701/29368787-50105b6e-82d3-11e7-97db-8e7710cd2d5f.png)

Any ideas?

**Comment by ssnepenthe** [comment]
You need `--full`, not `--fullPage`

**Comment by CaledoniaProject** [comment]
Thanks, do you know how to post data with chrome remote interface?
