### ISSUE TITLE
Image size of screenshots with single Chrome instance on linux are inconsistent

### ISSUE THREAD

**Issue by expaand** [schnerd/chrome-headless-screenshots#4]
Yes indeed, I had problems with the Mac, so went to Ubuntu via VMware (16.04.2). I have tried both Google Chrome 58.0.3029.110 , and Google Chrome 59.0.3071.71 beta, both with similar results:

Setting the viewportWidth and viewportHeight only would work correctly the first screenshot. Subsequent shots would result in a small image, not the one I wanted (1200,3000).

I have not succeeded in a workaround for this, other than restarting Chrome for each screenshot.

**Comment by arjunkomath** [comment]
@expaand  I'm facing the same issue. Most of the screenshots are in 800 x 600 resolution.

**Comment by expaand** [comment]
Actually, it turned out restarting Chrome for each screenshot doesn't work either, if you are asking for explicit viewportWidth and viewportHeight. I had to take *two* shots, of each site, and on the *second* shot, it would work! (Never figured out why *that* happens!). However, if you set the "full" flag, it works all the time. So that was a clue. 

I got it to work by always calling setVisibleSize twice. If the full flag is on, this is already being done. So if you want custom width and height, call it a second time (with the custom width and height).

I have no idea why this is, but I did get it to work consistently and reliably.

**Comment by arjunkomath** [comment]
@expaand That seems to work, you saved my day! 👍

**Comment by lichenbuliren** [comment]
I have the same issue, when i call `DOM.getBoxModel` it aways return the `viewportHeight` equal to 900 which is the init viewportHeight value.

here is result when i call `DOM.getBoxModel({nodeId: bodyNodeId})`;

```json
{
  model: {
    content: [0, 0, 1440, 0, 1440, 900, 0, 900],
    padding: [0, 0, 1440, 0, 1440, 900, 0, 900],
    border: [0, 0, 1440, 0, 1440, 900, 0, 900],
    margin: [0, 0, 1440, 0, 1440, 900, 0, 900],
    width: 1440,
    height: 900
  }
}
```

**Comment by gealbin** [comment]
Hi all, I had the same issue. I fixed this by running chrome with the argument window-size. I used this command to start chrome (in my case I need 720p screenshots):
`google-chrome --headless --window-size=1280x720 --hide-scrollbars --remote-debugging-port=9222 --disable-gpu &`

I hope this also work for someone else.

**Comment by schnerd** [comment]
Closing this issue – I'm recommending that users check out [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer) and report any issues with headless chrome there if necessary.
