### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by cowchimp** [schnerd/chrome-headless-screenshots#5]
Thanks.

**Comment by schnerd** [comment]
@cowchimp Thoughts on how to handle the fact that Chrome is a dependency? Can't really install it as an npm package–although I guess the script can check if it's running fail early with a friendly warning message.

**Comment by hellocosmin** [comment]
`npm install schnerd/chrome-headless-screenshots` is enough for me, but the warning message thing could be a solution, yeah.

**Comment by schnerd** [comment]
It looks like [chrome-launcher](https://www.npmjs.com/package/chrome-launcher) now exists, which would help out with this (in case anyone was thinking of making a PR for this)

**Comment by schnerd** [comment]
Closing this in favor of [puppeteer](https://github.com/GoogleChrome/puppeteer)
