### ISSUE TITLE
High DPI screenshots issue

### ISSUE THREAD

**Issue by 0fork** [schnerd/chrome-headless-screenshots#9]
Has anybody figured out how to emulate retina/high DPI successfully in screenshots with this script, or headless chrome in any way?

I need to test CSS media queries for higher pixel densities but no matter how I try to set deviceScaleFactor emulation, scaling etc. I still end up with 1x screenshots.

**Comment by schnerd** [comment]
@0fork it sounds like this is less an issue with our script, and more of an issue with chrome itself? have you explored the full [protocol API](https://chromedevtools.github.io/debugger-protocol-viewer/tot/
